'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const {
  sidecarPath,
  readSidecar,
  writeSidecar,
  clearSidecar,
  bumpMinor,
  rewriteVersionInSpec,
} = require('../lib/intelligence-loop/auto-nudge-sidecar');

describe('auto-nudge-sidecar: sidecarPath resolves alongside spec file', () => {
  test('default specialistsDir resolves to lib/specialists/<id>.auto-nudge.js', () => {
    const p = sidecarPath('test-id');
    expect(p.endsWith(path.join('lib', 'specialists', 'test-id.auto-nudge.js'))).toBe(true);
  });

  test('explicit specialistsDir override is honored', () => {
    const p = sidecarPath('foo', { specialistsDir: '/tmp/myspec' });
    expect(p).toBe(path.join('/tmp/myspec', 'foo.auto-nudge.js'));
  });
});

describe('auto-nudge-sidecar: read/write/clear round-trip', () => {
  let dir;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sidecar-test-'));
  });
  afterEach(() => {
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) {}
  });

  test('readSidecar returns null when file does not exist', () => {
    expect(readSidecar('missing-id', { specialistsDir: dir })).toBeNull();
  });

  test('writeSidecar creates a file readable by readSidecar', () => {
    const p = writeSidecar('s', 'NUDGE TEXT', {
      generatedAt: '2026-05-13T00:00:00Z',
      proposalId: 'autoprop-abc',
      cycleId: 'cycle-1',
      targetVersion: '0.3.0',
    }, { specialistsDir: dir });
    expect(fs.existsSync(p)).toBe(true);
    const text = readSidecar('s', { specialistsDir: dir });
    expect(text).toContain('NUDGE TEXT');
  });

  test('writeSidecar header carries audit metadata', () => {
    const p = writeSidecar('s', 'x', {
      proposalId: 'autoprop-xyz', cycleId: 'cycle-42', targetVersion: '0.7.0',
    }, { specialistsDir: dir });
    const raw = fs.readFileSync(p, 'utf8');
    expect(raw).toContain('AUTO-GENERATED by runFullCycle');
    expect(raw).toContain('Source proposal: autoprop-xyz');
    expect(raw).toContain('Cycle: cycle-42');
    expect(raw).toContain('Target version: 0.7.0');
  });

  test('writeSidecar escapes backticks and ${...} so the file is valid JS', () => {
    const tricky = 'has `backticks` and ${interpolation} attempts';
    writeSidecar('s', tricky, {}, { specialistsDir: dir });
    const text = readSidecar('s', { specialistsDir: dir });
    // After require(), the JS-side template literal evaluates back to the
    // original string. Both the backticks and the ${...} must survive.
    expect(text).toBe('\n' + tricky + '\n');
  });

  test('clearSidecar removes the file', () => {
    writeSidecar('s', 'x', {}, { specialistsDir: dir });
    expect(fs.existsSync(sidecarPath('s', { specialistsDir: dir }))).toBe(true);
    expect(clearSidecar('s', { specialistsDir: dir })).toBe(true);
    expect(fs.existsSync(sidecarPath('s', { specialistsDir: dir }))).toBe(false);
    expect(readSidecar('s', { specialistsDir: dir })).toBeNull();
  });

  test('clearSidecar returns false when file absent', () => {
    expect(clearSidecar('never-written', { specialistsDir: dir })).toBe(false);
  });

  test('repeated writeSidecar overwrites and require-cache is invalidated', () => {
    writeSidecar('s', 'FIRST', {}, { specialistsDir: dir });
    expect(readSidecar('s', { specialistsDir: dir })).toContain('FIRST');
    writeSidecar('s', 'SECOND', {}, { specialistsDir: dir });
    expect(readSidecar('s', { specialistsDir: dir })).toContain('SECOND');
    expect(readSidecar('s', { specialistsDir: dir })).not.toContain('FIRST');
  });
});

describe('auto-nudge-sidecar: bumpMinor version math', () => {
  test('0.2.0 -> 0.3.0', () => {
    expect(bumpMinor('0.2.0')).toBe('0.3.0');
  });
  test('0.9.0 -> 0.10.0 (no overflow to next major)', () => {
    expect(bumpMinor('0.9.0')).toBe('0.10.0');
  });
  test('1.4.7 -> 1.5.0 (patch resets to 0)', () => {
    expect(bumpMinor('1.4.7')).toBe('1.5.0');
  });
  test('throws on non-string input', () => {
    expect(() => bumpMinor(0.2)).toThrow(/string/);
  });
  test('throws on malformed input', () => {
    expect(() => bumpMinor('not-a-version')).toThrow(/M\.m\.p/);
    expect(() => bumpMinor('1.2')).toThrow(/M\.m\.p/);
    expect(() => bumpMinor('1.2.3.4')).toThrow(/M\.m\.p/);
  });
});

describe('auto-nudge-sidecar: rewriteVersionInSpec narrow regex', () => {
  let dir;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'spec-rewrite-test-'));
  });
  afterEach(() => {
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) {}
  });

  test('rewrites the version line and leaves everything else alone', () => {
    const specPath = path.join(dir, 'sample.js');
    const source = [
      "'use strict';",
      "const id = 'sample';",
      "const version = '0.2.0';",
      "const systemPrompt = `unchanged`;",
      "module.exports = { id, version, systemPrompt };",
      '',
    ].join('\n');
    fs.writeFileSync(specPath, source, 'utf8');
    const r = rewriteVersionInSpec(specPath, '0.3.0');
    expect(r.newVersion).toBe('0.3.0');
    const rewritten = fs.readFileSync(specPath, 'utf8');
    expect(rewritten).toContain("const version = '0.3.0';");
    expect(rewritten).toContain("const id = 'sample';");
    expect(rewritten).toContain('const systemPrompt = `unchanged`;');
  });

  test('throws when spec has no version declaration', () => {
    const specPath = path.join(dir, 'no-version.js');
    fs.writeFileSync(specPath, "const id = 'x';\nmodule.exports = { id };", 'utf8');
    expect(() => rewriteVersionInSpec(specPath, '0.3.0')).toThrow(/expected exactly one/);
  });

  test('throws when spec has multiple version declarations (ambiguous)', () => {
    const specPath = path.join(dir, 'two-versions.js');
    fs.writeFileSync(specPath, [
      "const version = '0.1.0';",
      "// later in file, a typo:",
      "const version = '0.2.0';",
    ].join('\n'), 'utf8');
    expect(() => rewriteVersionInSpec(specPath, '0.3.0')).toThrow(/expected exactly one/);
  });

  test('throws when spec file does not exist', () => {
    expect(() => rewriteVersionInSpec(path.join(dir, 'nope.js'), '0.3.0'))
      .toThrow(/not found/);
  });
});
